//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Inputs/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace _7DRL.Input.Controls
{
    public partial class @Controls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Controls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""61781f5c-df1a-4872-b695-e021a8f20121"",
            ""actions"": [
                {
                    ""name"": ""KnownCommands"",
                    ""type"": ""Button"",
                    ""id"": ""c8616259-7488-4c34-91b9-0642cd66212b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VolumeUp"",
                    ""type"": ""Button"",
                    ""id"": ""1cc83249-466b-4298-b556-c8375e56ed8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VolumeDown"",
                    ""type"": ""Button"",
                    ""id"": ""1e852a85-aa1c-4840-9960-aea7e0642a75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b039ec47-d12d-43d5-a8a1-2dfd762e812a"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KnownCommands"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be23dd6b-5d58-43f8-a923-9e086b6abd71"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VolumeUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d975d380-74d6-461e-af59-9841ebb18c55"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VolumeDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Main
            m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
            m_Main_KnownCommands = m_Main.FindAction("KnownCommands", throwIfNotFound: true);
            m_Main_VolumeUp = m_Main.FindAction("VolumeUp", throwIfNotFound: true);
            m_Main_VolumeDown = m_Main.FindAction("VolumeDown", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Main
        private readonly InputActionMap m_Main;
        private IMainActions m_MainActionsCallbackInterface;
        private readonly InputAction m_Main_KnownCommands;
        private readonly InputAction m_Main_VolumeUp;
        private readonly InputAction m_Main_VolumeDown;
        public struct MainActions
        {
            private @Controls m_Wrapper;
            public MainActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @KnownCommands => m_Wrapper.m_Main_KnownCommands;
            public InputAction @VolumeUp => m_Wrapper.m_Main_VolumeUp;
            public InputAction @VolumeDown => m_Wrapper.m_Main_VolumeDown;
            public InputActionMap Get() { return m_Wrapper.m_Main; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
            public void SetCallbacks(IMainActions instance)
            {
                if (m_Wrapper.m_MainActionsCallbackInterface != null)
                {
                    @KnownCommands.started -= m_Wrapper.m_MainActionsCallbackInterface.OnKnownCommands;
                    @KnownCommands.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnKnownCommands;
                    @KnownCommands.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnKnownCommands;
                    @VolumeUp.started -= m_Wrapper.m_MainActionsCallbackInterface.OnVolumeUp;
                    @VolumeUp.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnVolumeUp;
                    @VolumeUp.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnVolumeUp;
                    @VolumeDown.started -= m_Wrapper.m_MainActionsCallbackInterface.OnVolumeDown;
                    @VolumeDown.performed -= m_Wrapper.m_MainActionsCallbackInterface.OnVolumeDown;
                    @VolumeDown.canceled -= m_Wrapper.m_MainActionsCallbackInterface.OnVolumeDown;
                }
                m_Wrapper.m_MainActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @KnownCommands.started += instance.OnKnownCommands;
                    @KnownCommands.performed += instance.OnKnownCommands;
                    @KnownCommands.canceled += instance.OnKnownCommands;
                    @VolumeUp.started += instance.OnVolumeUp;
                    @VolumeUp.performed += instance.OnVolumeUp;
                    @VolumeUp.canceled += instance.OnVolumeUp;
                    @VolumeDown.started += instance.OnVolumeDown;
                    @VolumeDown.performed += instance.OnVolumeDown;
                    @VolumeDown.canceled += instance.OnVolumeDown;
                }
            }
        }
        public MainActions @Main => new MainActions(this);
        public interface IMainActions
        {
            void OnKnownCommands(InputAction.CallbackContext context);
            void OnVolumeUp(InputAction.CallbackContext context);
            void OnVolumeDown(InputAction.CallbackContext context);
        }
    }
}
